"""Test actual standalone HTML, DOM/canvas and touch dispatch in Chromium.
No application, model, network or storage test doubles. Browser network navigation
is blocked here; file-origin persistence and service-worker lifecycle remain unverified.
"""
import asyncio,json,os
from pathlib import Path
from playwright.async_api import async_playwright
ROOT=Path(__file__).resolve().parents[1]
async def main():
 checks=[];errors=[];requests=[];metrics={}
 async with async_playwright() as p:
  browser=await p.chromium.launch(executable_path=os.environ.get('CHROMIUM_PATH','/usr/bin/chromium'),headless=True,args=['--no-sandbox'])
  async def check(name,value):
   if not value:raise AssertionError(name)
   checks.append(name);print("PASS",name,flush=True)
  async def boot(page):
   page.set_default_timeout(6000)
   page.on('pageerror',lambda e:errors.append(str(e)))
   page.on('request',lambda r:requests.append(r.url))
   await page.set_content((ROOT/'preview/spot-v4.7.html').read_text(),wait_until='load');await page.wait_for_function('!!window.SpotDemo');await page.wait_for_timeout(100)
  page=await browser.new_page(viewport={'width':1440,'height':960})
  await boot(page)
  await check('region includes all 32 venue IDs without duplicate markers',await page.evaluate("(()=>{const ids=[...document.querySelectorAll('[data-members]')].flatMap(e=>e.dataset.members.split(','));return ids.length===32&&new Set(ids).size===32})()"))
  await check('all regional markers sum to 610 participating demo accounts',await page.evaluate("[...document.querySelectorAll('[data-count][data-members]')].reduce((n,e)=>n+Number(e.dataset.count),0)===610"))
  await check('map no longer displays naked number-only markers',await page.locator('.activity-marker').evaluate_all("xs=>xs.length>0&&xs.every(x=>x.querySelector('.activity-marker-title')&&/app users?|No recent data/.test(x.innerText))"))
  await check('every marker is a labeled keyboard-accessible button',await page.locator('.activity-marker').evaluate_all("xs=>xs.every(x=>x.tagName==='BUTTON'&&x.getAttribute('aria-label').includes('Not total occupancy'))"))
  await check('new fixture count is reflected in the UI', '32 places' in await page.locator('#placeCount').inner_text() and await page.locator('#presentCount').inner_text()=='610')
  await page.click('[data-action="city"]');await page.wait_for_timeout(150)
  await page.screenshot(path=ROOT/'artifacts/v47-map-desktop-light.png')
  await check('city view contains readable category icons',await page.locator('.activity-marker-symbol').count()>0)
  await page.click('[data-action="downtown"]');await page.wait_for_timeout(150)
  await check('downtown still exposes fictional venues',await page.locator('.activity-marker').count()>0)
  await check('desktop page has no horizontal overflow',await page.evaluate('document.documentElement.scrollWidth<=innerWidth'))
  await check('no Ask button or assistant panel remains',await page.locator('#askSpot,#spotAssistantPanel,iframe').count()==0)
  await check('no assistant runtime globals remain',await page.evaluate("typeof SpotAssistantMap==='undefined'&&typeof SpotAssistantContext==='undefined'"))
  venues=await page.evaluate('SpotCore.VENUES.map(v=>({id:v.id,name:v.name,category:v.category}))')
  for v in venues:
   await page.locator(f'[data-venue="{v["id"]}"]').first.click()
   header=await page.locator('.venue-cover-type').inner_text()
   expected='Café' if v['category']=='cafe' else 'Bar / club'
   await check(f'{v["name"]}: full title and category illustration',await page.locator('#detailTitle').inner_text()==v['name'] and header==expected and await page.locator('.cover-word').count()==0)
  await page.locator('[data-venue="juniper"]').first.click()
  await check('details do not block search or map with a modal overlay',await page.locator('.detail-card').get_attribute('role')=='region' and await page.locator('.modal-overlay').count()==0)
  await page.locator('.detail-card [data-save="juniper"]').click()
  await check('save works from the new overview',await page.evaluate("SpotDemo.getState().savedVenues.includes('juniper')"))
  await page.locator('.detail-card [data-compare="juniper"]').click()
  await page.locator('[data-venue="common"]').first.click()
  await page.locator('.detail-card [data-compare="common"]').click()
  await page.locator('[data-action="review-compare"]').click()
  await check('comparison retains the selected venues',await page.locator('.comparison-card').is_visible() and 'Juniper Coffee' in await page.locator('.comparison-card').inner_text() and 'Common Ground' in await page.locator('.comparison-card').inner_text())
  await page.locator('#venueSearch').fill('East Campus');await page.wait_for_timeout(150)
  await check('area search works while a comparison is open',await page.evaluate("SpotDemo.getSearchArea()?.name==='East Campus'"))
  await page.evaluate('SpotDemo.reset()');await page.wait_for_timeout(100)
  await page.locator('[data-venue="juniper"]').first.click()
  await page.screenshot(path=ROOT/'artifacts/v47-cafe-desktop-light.png')
  await page.locator('.detail-card [data-action="directions"]').click()
  await check('directions remain a preview for fictional venues','fictional' in (await page.locator('.modal').inner_text()).lower())
  await page.locator('[data-action="close-modal"]').first.click()
  await page.locator('.detail-card [data-action="share-place"]').click()
  await check('place sharing opens without chat UI',await page.locator('.modal').is_visible() and await page.locator('iframe').count()==0)
  await page.locator('[data-action="close-modal"]').first.click()
  await page.locator('[data-theme-toggle]').click();await page.locator('[data-theme-choice="dark"]').click()
  club=next(v for v in venues if v['category']!='cafe')
  await page.locator(f'[data-venue="{club["id"]}"]').first.click()
  await page.screenshot(path=ROOT/'artifacts/v47-club-desktop-dark.png')
  await check('nightlife cover has a glass illustration in dark mode',await page.locator('.cover-glass-fill').count()==1 and await page.locator('html').get_attribute('data-theme')=='dark')
  await page.evaluate('SpotDemo.reset()');await page.wait_for_timeout(100)
  await page.set_viewport_size({'width':390,'height':844});await page.wait_for_timeout(100)
  overlap_count=await page.evaluate("""()=>{let overlaps=0;const v=SpotCore.venueById('juniper');for(const z of [.5,.7,.85,1,1.4,2]){SpotDemo.setCamera({x:v.x,y:v.y,zoom:z});SpotDemo.flushMap();const vr=document.querySelector('#mapViewport').getBoundingClientRect();const boxes=[...document.querySelectorAll('.activity-marker')].map(e=>e.getBoundingClientRect()).filter(r=>r.x>=0&&r.right<=innerWidth&&r.y>vr.y+60&&r.bottom<vr.bottom-170);for(let i=0;i<boxes.length;i++)for(let j=i+1;j<boxes.length;j++){const a=boxes[i],b=boxes[j];if(a.x<b.right&&a.right>b.x&&a.y<b.bottom&&a.bottom>b.y)overlaps++;}}return overlaps}""")
  await check('readable cards do not overlap across tested mobile downtown zooms',overlap_count==0)
  for width,height in [(320,740),(360,800),(390,844),(430,932)]:
   await page.set_viewport_size({'width':width,'height':height});await page.wait_for_timeout(100)
   await page.locator('#venueSearch').fill('East Campus');await page.wait_for_timeout(150)
   await check(f'{width}px: area search still targets East Campus',await page.evaluate("SpotDemo.getSearchArea()?.name==='East Campus'"))
   await check(f'{width}px: no horizontal page overflow',await page.evaluate('document.documentElement.scrollWidth<=innerWidth'))
   await check(f'{width}px: markers retain 52px touch surfaces',await page.locator('.activity-marker').evaluate_all('xs=>xs.every(x=>x.offsetHeight>=52&&x.offsetWidth>=144)'))
   await check(f'{width}px: counts fit inside their labels',await page.locator('.activity-marker-count').evaluate_all('xs=>xs.every(x=>x.scrollWidth<=x.clientWidth+1)'))
   await check(f'{width}px: campus buildings are drawn on the canvas',await page.evaluate('SpotDemo.getRenderStats().cartography.buildings>0'))
   # Render via the real venue click handler, without relying on an offscreen list's hitbox.
   await page.locator('#venueSearch').fill('Juniper Coffee');await page.wait_for_timeout(120)
   await page.locator('[data-venue="juniper"]').first.evaluate('(el)=>el.click()')
   await check(f'{width}px: overview retains full title',await page.locator('#detailTitle').inner_text()=='Juniper Coffee')
   await check(f'{width}px: compact category artwork is visible',(await page.locator('.venue-cover').bounding_box())['height']==48 and await page.locator('.venue-cover-art').is_visible())
   await check(f'{width}px: overview title fits without horizontal truncation',await page.locator('#detailTitle').evaluate('(el)=>el.scrollWidth<=el.clientWidth+1'))
   await check(f'{width}px: close control has at least a 42px touch target',(await page.locator('.venue-cover-close').bounding_box())['height']>=42)
   await page.locator('[data-action="expand-detail"]').click()
   await check(f'{width}px: expanded details preserve sample history',await page.locator('.detail-card.expanded .activity-timeline').is_visible())
   if width==390:await page.screenshot(path=ROOT/'artifacts/v47-cafe-mobile-dark.png')
   await page.locator('[data-action="close-detail"]').click()
   await page.locator('#venueSearch').fill('');await page.wait_for_timeout(50)
  await page.set_viewport_size({'width':390,'height':844});await page.wait_for_timeout(100)
  await page.locator('#venueSearch').fill('East Campus');await page.wait_for_timeout(150)
  await page.click('[data-theme-toggle]');await page.click('[data-theme-choice="dark"]');await page.wait_for_timeout(150)
  await check('dark mode still applies to the map',await page.locator('html').get_attribute('data-theme')=='dark')
  await page.screenshot(path=ROOT/'artifacts/v47-map-mobile-dark.png')
  # The activity display must never turn expiry into a quiet/full assertion.
  await page.evaluate('SpotDemo.advanceTime(15*60*1000)');await page.wait_for_timeout(100)
  await check('expired observations read No recent data',await page.locator('.activity-marker').evaluate_all("xs=>xs.every(x=>x.innerText.includes('No recent data'))"))
  await check('expiry clears all current venue contributions',await page.evaluate("SpotCore.VENUES.every(v=>!SpotDemo.getActivity(v.id).hasData)"))
  await page.close()
  settings=await browser.new_page(viewport={'width':1280,'height':900})
  await boot(settings)
  await settings.locator('.desktop-nav [data-screen="friends"]').click()
  await check('friends screen still has the 60 accepted demo friends',await settings.evaluate("Object.values(SpotDemo.getState().relations).filter(v=>v==='accepted').length===60"))
  await settings.locator('.desktop-nav [data-screen="privacy"]').click()
  await check('privacy starts with both sharing modes off',await settings.evaluate('!SpotDemo.getState().sharing&&!SpotDemo.getState().friendSharing'))
  await settings.locator('[data-action="toggle-sharing"]').click()
  await settings.locator('[data-action="enable-sharing"]').click()
  await check('count contribution can still be enabled without friend visibility',await settings.evaluate('SpotDemo.getState().sharing&&!SpotDemo.getState().friendSharing'))
  await settings.locator('[data-action="toggle-friend-sharing"]').click()
  await settings.locator('[data-audience]').first.check()
  await settings.locator('[data-action="save-audience"]').click()
  await check('friend visibility still requires choosing an audience',await settings.evaluate('SpotDemo.getState().friendSharing&&SpotDemo.getState().shareWith.length===1'))
  await settings.locator('[data-action="toggle-friend-sharing"]').click()
  await check('turning off named sharing preserves count contribution',await settings.evaluate('SpotDemo.getState().sharing&&!SpotDemo.getState().friendSharing'))
  await settings.locator('[data-action="pause-all"]').click()
  await check('pause all still turns both sharing modes off',await settings.evaluate('!SpotDemo.getState().sharing&&!SpotDemo.getState().friendSharing'))
  await settings.close()
  # Trusted Chromium touch events on a mobile-emulated page (not a real phone).
  context=await browser.new_context(viewport={'width':390,'height':844},is_mobile=True,has_touch=True,device_scale_factor=2)
  mobile=await context.new_page();await boot(mobile);cdp=await context.new_cdp_session(mobile)
  async def touch(kind,points):
   await cdp.send('Input.dispatchTouchEvent',{'type':kind,'touchPoints':[{'x':x,'y':y,'id':i,'radiusX':3,'radiusY':3,'force':1} for i,x,y in points]})
  await mobile.evaluate("(()=>{const v=SpotCore.venueById('juniper');SpotDemo.setCamera({x:v.x,y:v.y,zoom:1.4})})()");await mobile.wait_for_timeout(100)
  before=await mobile.evaluate('SpotDemo.getCamera()');await touch('touchStart',[(1,195,365)]);await touch('touchMove',[(1,255,405)]);await touch('touchEnd',[]);await mobile.wait_for_timeout(100)
  after=await mobile.evaluate('SpotDemo.getCamera()')
  await check('one finger pans without changing zoom',before['zoom']==after['zoom'] and (before['x']!=after['x'] or before['y']!=after['y']))
  await check('single-finger pan does not open a place',await mobile.evaluate('SpotDemo.getSelectedVenueId()===null'))
  before=await mobile.evaluate('SpotDemo.getCamera()');await touch('touchStart',[(1,140,375),(2,240,375)]);await touch('touchMove',[(1,115,375),(2,265,375)]);await mobile.wait_for_timeout(70)
  after=await mobile.evaluate('SpotDemo.getCamera()');await check('two-finger pinch outward zooms in',after['zoom']>before['zoom'])
  await touch('touchMove',[(1,155,375),(2,225,375)]);await mobile.wait_for_timeout(70);smaller=await mobile.evaluate('SpotDemo.getCamera()');await check('two-finger pinch inward zooms out',smaller['zoom']<after['zoom']);await touch('touchEnd',[])
  await mobile.click('[data-action="region"]');await mobile.wait_for_timeout(150)
  # Choose a group actually hit-testable, not covered by map controls/cards.
  key=await mobile.evaluate("(()=>{for(const n of document.querySelectorAll('[data-cluster]')){const r=n.getBoundingClientRect();if(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2)?.closest('[data-cluster]')===n)return n.dataset.cluster}return null})()")
  await check('at least one regional group is reachable by touch',bool(key))
  before=await mobile.evaluate('SpotDemo.getCamera()');await mobile.locator(f'[data-cluster="{key}"]').tap();await mobile.wait_for_timeout(120);after=await mobile.evaluate('SpotDemo.getCamera()')
  await check('tapping a group jumps inward, not a pinch instruction',after['zoom']>before['zoom'])
  await mobile.evaluate("(()=>{const v=SpotCore.venueById('juniper');SpotDemo.setCamera({x:v.x,y:v.y,zoom:2})})()");await mobile.wait_for_timeout(100)
  rect=await mobile.locator('[data-pin="juniper"]').bounding_box();x=rect['x']+rect['width']/2;y=rect['y']+rect['height']/2
  before=await mobile.evaluate('SpotDemo.getCamera()');await touch('touchStart',[(1,x,y)]);await touch('touchMove',[(1,x+50,y+30)]);await touch('touchEnd',[]);await mobile.wait_for_timeout(100)
  await check('dragging from a label pans without opening it',await mobile.evaluate('SpotDemo.getSelectedVenueId()===null'))
  await check('dragging from a label never zooms',before['zoom']==(await mobile.evaluate('SpotDemo.getCamera()'))['zoom'])
  await mobile.evaluate("(()=>{const v=SpotCore.venueById('juniper');SpotDemo.setCamera({x:v.x,y:v.y,zoom:2})})()");await mobile.wait_for_timeout(70)
  await mobile.locator('[data-pin="juniper"]').tap();await mobile.wait_for_timeout(100)
  await check('tapping a venue opens its actual detail card',await mobile.locator('#detailTitle').inner_text()=='Juniper Coffee')
  await mobile.locator('#venueSearch').fill('East Campus');await mobile.wait_for_timeout(120)
  await check('search still works without closing place details',await mobile.evaluate("SpotDemo.getSearchArea()?.name==='East Campus'"))
  before=await mobile.evaluate('SpotDemo.getRenderStats().clusterBuilds')
  await mobile.evaluate("(()=>{let c=SpotDemo.getCamera();for(let i=0;i<20;i++){SpotDemo.setCamera({x:c.x+i*2});SpotDemo.flushMap()}})()")
  after=await mobile.evaluate('SpotDemo.getRenderStats().clusterBuilds');await check('repeated same-scale pan reuses clusters',before==after)
  metrics=await mobile.evaluate('SpotDemo.getRenderStats()')
  await check('standalone makes no external requests',len(requests)==0)
  await check('no uncaught UI script errors',not errors)
  await browser.close()
 report={'passed':len(checks),'failed':0,'checks':checks,'errors':errors,'requests':requests,'renderSample':metrics,'method':'Actual standalone HTML loaded by set_content, real DOM/canvas and Chromium touch events, no model/network/storage doubles. Browser navigation is administratively blocked; service-worker lifecycle and file-origin storage durability are not verified. Physical phones and mobile Safari were not tested.'}
 (ROOT/'artifacts/browser-tests.json').write_text(json.dumps(report,indent=2)+'\n');print(json.dumps(report,indent=2))
asyncio.run(main())
