"""UI/bridge test on a no-network srcdoc fixture; not real-model validation."""
import asyncio,json,os
from pathlib import Path
from playwright.async_api import async_playwright
from integration_harness import parent_html,parent_script
ROOT=Path(__file__).resolve().parents[1]
async def main():
 checks=[];errors=[]
 async with async_playwright() as p:
  browser=await p.chromium.launch(executable_path=os.environ.get('CHROMIUM_PATH','/usr/bin/chromium'),headless=True,args=['--no-sandbox'])
  page=await browser.new_page(viewport={'width':1440,'height':960})
  page.on('pageerror',lambda e:errors.append(str(e)))
  async def check(name,value):
   if not value:raise AssertionError(name)
   checks.append(name)
  await page.set_content(parent_html());await page.add_script_tag(content=parent_script());await page.wait_for_function('!!window.SpotDemo')
  await check('Map starts normally',await page.locator('#mapViewport').is_visible())
  await check('Assistant loads lazily',await page.locator('iframe').count()==0)
  before=await page.evaluate('SpotDemo.getState()')
  await page.click('#askSpot');fr=page.frame_locator('#spotAssistantFrame')
  await fr.locator('#boot-notice').wait_for(state='hidden',timeout=12000)
  await check('Embedded assistant opens',await fr.locator('#welcome').is_visible())
  await check('Context bridge receives public demo data','Lincoln & nearby' in await fr.locator('#spot-context-note').inner_text())
  await check('Model does not auto-load','No model loaded' in await fr.locator('#model-status').inner_text())
  await check('Frame theme follows parent',await fr.locator('html').get_attribute('data-theme')==await page.locator('html').get_attribute('data-theme'))
  await check('No desktop overflow',await page.evaluate('document.documentElement.scrollWidth<=innerWidth'))
  await page.screenshot(path=ROOT/'artifacts/spot-ai-desktop-light.png')
  await fr.locator('#composer').fill('Find demo cafés around East Campus')
  await fr.locator('#send').click()
  await check('Sending without model preserves draft',await fr.locator('#composer').input_value()=='Find demo cafés around East Campus')
  await check('No-model submit opens setup',await fr.locator('#panel-dialog').is_visible())
  await fr.locator('#close-panel').click();await page.click('#closeSpotAssistant')
  await check('Closing returns to map',not await page.locator('#spotAssistantPanel').is_visible() and await page.locator('#mapViewport').is_visible())
  await check('Closing restores launcher focus',await page.locator('#askSpot').evaluate('(e)=>e===document.activeElement'))
  await page.click('#askSpot')
  await check('Draft survives panel close',await fr.locator('#composer').input_value()=='Find demo cafés around East Campus')
  await check('Reopening reuses one frame',await page.locator('iframe').count()==1)
  await fr.locator('#welcome-load').click();await fr.locator('#load-model').click()
  await check('Explicit model approval required',await fr.locator('#confirm-dialog').is_visible())
  await fr.locator('#confirm-no').click();await check('Declining leaves model unloaded','No model loaded' in await fr.locator('#model-status').inner_text())
  await fr.locator('#load-model').click();await fr.locator('#confirm-yes').click()
  await fr.locator('#composer').fill('Find demo cafés around East Campus');await fr.locator('#send').click()
  await fr.locator('.message.assistant .source-item').first.wait_for(timeout=10000)
  await fr.locator('#stop').wait_for(state='hidden',timeout=20000)
  await check('Test reply renders; model is explicitly a fixture',await fr.locator('.message.assistant').count()==1 and 'TEST FIXTURE' in await fr.locator('#privacy-note').inner_text())
  await check('Retrieved map sources include East Campus','East Campus' in await fr.locator('.message.assistant .sources').inner_text())
  await check('Map links appear in factual source cards',await fr.locator('.spot-source-action').count()>=1)
  await fr.locator('.source-item').first.locator('summary').click();await fr.locator('.spot-source-action').first.click();await page.locator('#spotAssistantPanel').wait_for(state='hidden',timeout=5000)
  await check('Source action returns to the map',not await page.locator('#spotAssistantPanel').is_visible())
  await check('Area source focuses East Campus',await page.evaluate("SpotDemo.getSearchArea()?.name==='East Campus'"))
  await page.click('#askSpot');await fr.locator('#toggle-sidebar').click();await fr.locator('#new-chat').click()
  await check('New conversation works in panel',await fr.locator('#welcome').is_visible())
  # A forged parent-window message must not be treated as the child frame.
  await page.evaluate("window.dispatchEvent(new MessageEvent('message',{origin:location.origin,source:window,data:{channel:'spot-assistant-v1',type:'navigate',action:{type:'area',id:'haymarket'}}}))")
  await check('Bridge rejects wrong-source navigation',await page.evaluate("SpotDemo.getSearchArea()?.name==='East Campus'"))
  await page.evaluate("document.documentElement.dataset.theme='dark';dispatchEvent(new CustomEvent('spot-theme-change'))")
  await page.wait_for_timeout(100)
  await check('Dark mode synchronizes into assistant',await fr.locator('html').get_attribute('data-theme')=='dark')
  await page.set_viewport_size({'width':390,'height':844});await page.wait_for_timeout(200)
  await check('No mobile page overflow',await page.evaluate('document.documentElement.scrollWidth<=innerWidth'))
  await check('No mobile frame overflow',await fr.locator('html').evaluate('(e)=>e.scrollWidth<=innerWidth'))
  await check('Mobile navigation remains visible',await page.locator('#mobileNavigation').is_visible())
  await page.screenshot(path=ROOT/'artifacts/spot-ai-mobile-dark.png')
  await fr.locator('#toggle-sidebar').click();await check('Chat list still accessible',await fr.locator('#new-chat').is_visible())
  await fr.locator('#sidebar-scrim').click(position={'x':320,'y':200});await fr.locator('#welcome-load').click()
  await check('Tools default safely',not await fr.locator('[data-setting="wikipedia"]').is_checked() and not await fr.locator('[data-setting="memory"]').is_checked())
  await page.screenshot(path=ROOT/'artifacts/spot-ai-mobile-settings.png')
  await fr.locator('#close-panel').click();await page.click('#closeSpotAssistant')
  await check('Original relations unchanged',await page.evaluate('SpotDemo.getState().relations')==before['relations'])
  await check('Original privacy controls unchanged',await page.evaluate('SpotDemo.getState().sharing')==before['sharing'] and await page.evaluate('SpotDemo.getState().friendSharing')==before['friendSharing'])
  await check('No uncaught script errors',not errors)
  await browser.close()
 report={'passed':len(checks),'failed':0,'checks':checks,'errors':errors,'method':'Opaque-origin srcdoc UI harness. Model, storage, worker, fetch are test doubles. Not real model inference, real-origin iframe certification or device testing.'}
 (ROOT/'artifacts/integration-browser.json').write_text(json.dumps(report,indent=2)+'\n');print(json.dumps(report,indent=2))
asyncio.run(main())
