'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),M=require('../map-core.js'),C=require('../core.js');
test('clustering conserves every venue exactly once at each scale',()=>{for(const z of [.025,.07,.15,.4,1,2,4,8]){const g=M.cluster(C.VENUES,z,'juniper');const ids=g.flatMap(g=>g.ids);assert.equal(ids.length,336);assert.equal(new Set(ids).size,336);}});
test('selected establishment stays independently selectable',()=>{const g=M.cluster(C.VENUES,.1,'juniper');assert.deepEqual(g.find(g=>g.ids.includes('juniper')).ids,['juniper']);});
test('cluster coordinates are member centroids',()=>{for(const g of M.cluster(C.VENUES,.1)){const vs=g.ids.map(C.venueById);assert.ok(Math.abs(g.x-vs.reduce((n,v)=>n+v.x,0)/vs.length)<.001);}});
test('zooming increases geographic separation',()=>assert.ok(M.cluster(C.VENUES,8).length>M.cluster(C.VENUES,.05).length));
test('cluster assignment is deterministic',()=>assert.deepEqual(M.cluster(C.VENUES,.2),M.cluster(C.VENUES,.2)));
test('clustering handles an empty search result',()=>assert.deepEqual(M.cluster([],1),[]));
test('cursor-anchored zoom preserves the pointed-at world coordinate',()=>{const c={x:200,y:100,zoom:.5},d={centerX:500,centerY:300},p={x:720,y:180};const wx=c.x+(p.x-d.centerX)/c.zoom,wy=c.y+(p.y-d.centerY)/c.zoom;const n=M.anchoredZoom(c,1.8,p,d);assert.ok(Math.abs(wx-(n.x+(p.x-d.centerX)/n.zoom))<1e-9);assert.ok(Math.abs(wy-(n.y+(p.y-d.centerY)/n.zoom))<1e-9);});
test('zoom respects configured boundaries',()=>{const c={x:0,y:0,zoom:1},d={centerX:0,centerY:0};assert.equal(M.anchoredZoom(c,100,d,d,.025,8).zoom,8);assert.equal(M.anchoredZoom(c,.0001,d,d,.025,8).zoom,.025);});
test('regional geographic extent is wider than the previous city extent',()=>{assert.ok(C.MAP.bounds.west< -97.1);assert.ok(C.MAP.bounds.east> -96.4);assert.ok(C.MAP.bounds.north>41);assert.ok(C.MAP.bounds.south<40.6);});
test('all twelve surrounding towns have searchable fictional places',()=>{const snap=C.makeSnapshot(),s=C.initialState();for(const area of C.MAP.areas.filter(a=>a.regional)){s.query=area.name;assert.ok(C.filteredVenues(s,snap,Date.now()).some(v=>v.area===area.name),area.name);}});
