import test,{before,after} from 'node:test';import assert from 'node:assert/strict';import http from 'node:http';import {spawn} from 'node:child_process';import {once} from 'node:events';
const port=4468,backendPort=4466;let app,fake,lastRequest,remote=false;const base=`http://127.0.0.1:${port}`;
before(async()=>{fake=http.createServer(async(req,res)=>{if(req.url==='/api/tags'){res.writeHead(200,{'Content-Type':'application/json'});return res.end('{"models":[]}');}let input='';for await(const chunk of req)input+=chunk;if(req.url==='/api/show'){res.writeHead(200,{'Content-Type':'application/json'});return res.end(JSON.stringify(remote?{remote_host:'https://remote.invalid',remote_model:'remote'}:{details:{format:'gguf'}}));}lastRequest=JSON.parse(input);res.writeHead(200,{'Content-Type':'application/x-ndjson'});res.write('{"message":{"content":"Fixture "}}\n');setTimeout(()=>res.end('{"message":{"content":"response"},"done":true,"eval_count":2}\n'),25);});fake.listen(backendPort,'127.0.0.1');await once(fake,'listening');app=spawn(process.execPath,['server.mjs'],{env:{...process.env,PORT:String(port),SANDBOX_PORT:String(port+1),LOCAL_BACKEND:'ollama',LOCAL_BACKEND_URL:`http://127.0.0.1:${backendPort}`,LOCAL_MODEL:'fixture-model',LOCAL_CHAT_TEST:'1'},stdio:'pipe'});let ready=false;for(let i=0;i<50;i++){try{const r=await fetch(base+'/api/status');if(r.ok){ready=true;break;}}catch{}await new Promise(r=>setTimeout(r,50));}assert.ok(ready,'Local test server started');});
after(async()=>{app?.kill('SIGTERM');await new Promise(r=>fake?.close(r));});
test('server reports explicit backend and test mode without keys',async()=>{const d=await(await fetch(base+'/api/status')).json();assert.equal(d.backend,'ollama');assert.equal(d.testMode,true);assert.equal(d.model,'fixture-model');});
test('static response applies CSP, COOP and COEP',async()=>{const r=await fetch(base+'/');assert.equal(r.status,200);assert.equal(r.headers.get('cross-origin-opener-policy'),'same-origin');assert.equal(r.headers.get('cross-origin-embedder-policy'),'require-corp');assert.match(r.headers.get('content-security-policy'),/object-src 'none'/);assert.match(await r.text(),/Open Ask Spot assistant/);});
test('cross-origin requests and unapproved hosts fail closed',async()=>{assert.equal((await fetch(base+'/api/status',{headers:{Origin:'https://hostile.example'}})).status,403);const status=await new Promise((resolve,reject)=>{const r=http.get(base+'/api/status',{headers:{Host:'hostile.example'}},res=>{res.resume();resolve(res.statusCode);});r.on('error',reject);});assert.equal(status,403);});
test('generation is streamed and uses only configured model and capped options',async()=>{const r=await fetch(base+'/api/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model:'attacker-model',messages:[{role:'user',content:'hello'}],temperature:50,max_tokens:9000})});assert.equal(r.headers.get('x-stream-format'),'ndjson');assert.match(await r.text(),/Fixture/);assert.equal(lastRequest.model,'fixture-model');assert.equal(lastRequest.options.temperature,1.5);assert.equal(lastRequest.options.num_predict,1536);});
test('constrained schemas are passed to Ollama format',async()=>{const schema={type:'object',properties:{tool:{type:'string'}}};const r=await fetch(base+'/api/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages:[{role:'user',content:'plan'}],response_format:{json_schema:{schema}}})});await r.text();assert.deepEqual(lastRequest.format,schema);});
test('malformed generation and unsupported roles are rejected',async()=>{for(const body of ['no json',JSON.stringify({messages:[{role:'tool',content:'x'}]})]){const r=await fetch(base+'/api/generate',{method:'POST',body});assert.equal(r.status,400);}});
test('Wikipedia cannot be triggered with an image-style GET',async()=>{assert.equal((await fetch(base+'/api/wiki?q=secret')).status,405);});
test('byte ranges and HEAD serve local assets correctly',async()=>{const r=await fetch(base+'/app.css',{headers:{Range:'bytes=0-9'}});assert.equal(r.status,206);assert.equal((await r.arrayBuffer()).byteLength,10);const h=await fetch(base+'/app.css',{method:'HEAD'});assert.ok(Number(h.headers.get('content-length'))>1000);assert.equal((await h.text()).length,0);});
test('offline manifest contains the whole app source and no API paths',async()=>{const d=await(await fetch(base+'/shell-manifest.json')).json();assert.ok(d.files.includes('/src/app.js'));assert.ok(d.files.includes('/workers/model.worker.js'));assert.ok(!d.files.some(p=>p.startsWith('/api/')));});
test('Python asset origin exposes neither application APIs nor chat source',async()=>{const sandbox=`http://127.0.0.1:${port+1}`;assert.equal((await fetch(sandbox+'/api/status')).status,404);assert.equal((await fetch(sandbox+'/src/app.js')).status,404);const r=await fetch(sandbox+'/');assert.equal(r.status,200);assert.match(r.headers.get('content-security-policy'),/connect-src 'self'/);});

test('cloud-model aliases are rejected before a chat is forwarded',async()=>{remote=true;lastRequest=null;try{const r=await fetch(base+'/api/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages:[{role:'user',content:'Never send this remotely'}]})});assert.equal(r.status,403);assert.match((await r.json()).error,/Cloud-backed/);assert.equal(lastRequest,null);}finally{remote=false;}});

test('Spot root loads map assets and lazily creates the assistant',async()=>{const text=await(await fetch(base+'/')).text();assert.match(text,/id="askSpot"/);assert.match(text,/src="\/spot\/app.js"/);assert.ok(!text.includes('<iframe'));assert.ok(!/<script>(?!\s*$)/.test(text));});
test('assistant page is same-origin and carries Spot-specific content',async()=>{const r=await fetch(base+'/assistant.html?embed=spot');assert.equal(r.status,200);assert.match(r.headers.get('content-security-policy'),/frame-ancestors 'self'/);assert.match((await r.text()),/Find your next spot/);});
test('frame policy permits own assistant but not arbitrary HTTPS origins',async()=>{const c=(await fetch(base+'/')).headers.get('content-security-policy');assert.match(c,/frame-src 'self' http:\/\/localhost:/);assert.ok(!c.includes('frame-src *'));assert.ok(!c.includes("script-src 'self' 'unsafe-inline'"));});
test('every offline-shell asset exists',async()=>{const d=await(await fetch(base+'/shell-manifest.json')).json();assert.ok(d.files.includes('/assistant.html'));assert.ok(d.files.includes('/assistant-embed.css'));assert.ok(d.files.includes('/spot/map-gestures.js'));for(const url of d.files){assert.equal((await fetch(base+url)).status,200,url);}});
test('rollback and server source are not exposed by the static server',async()=>{assert.equal((await fetch(base+'/rollback/spot-lincoln-v4.4.html')).status,404);assert.equal((await fetch(base+'/server.mjs')).status,404);});
