import test,{before,after} from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import http from 'node:http';
import {createServer} from '../server.mjs';
let server,base,port;
before(async()=>{server=createServer();server.listen(0,'127.0.0.1');await once(server,'listening');port=server.address().port;base=`http://127.0.0.1:${port}`;});
after(async()=>{server.closeAllConnections();await new Promise(resolve=>server.close(resolve));});
test('actual HTTP server returns the current map',async()=>{const r=await fetch(base);assert.equal(r.status,200);const s=await r.text();assert.match(s,/Spot v4.7/);assert.doesNotMatch(s,/askSpot|assistant/);});
test('health identifies the map-only release',async()=>{const r=await fetch(base+'/health');assert.deepEqual(await r.json(),{ok:true,app:'Spot',version:'4.7.0'});});
for(const pathname of ['/assistant.html','/spot/assistant-shell.js','/api/status','/api/chat','/api/wikipedia','/models/manifest.json','/sandbox/frame.html'])test(`removed endpoint returns 404: ${pathname}`,async()=>{const r=await fetch(base+pathname);assert.equal(r.status,404);});
test('POST cannot trigger a former model endpoint',async()=>{const r=await fetch(base+'/api/chat',{method:'POST',body:'{}'});assert.equal(r.status,405);assert.equal(r.headers.get('allow'),'GET, HEAD');});
test('HEAD returns correct metadata without a response body',async()=>{const r=await fetch(base+'/spot/venue-cover.js',{method:'HEAD'});assert.equal(r.status,200);assert.equal(await r.text(),'');assert.ok(Number(r.headers.get('content-length'))>0);});
test('static header disables microphone and location',async()=>{const r=await fetch(base);assert.match(r.headers.get('permissions-policy'),/microphone=\(\)/);assert.match(r.headers.get('permissions-policy'),/geolocation=\(\)/);assert.match(r.headers.get('content-security-policy'),/frame-src 'none'/);});
test('a query string does not break a static asset',async()=>{const r=await fetch(base+'/spot/venue-cover.css?v=4.7');assert.equal(r.status,200);assert.match(r.headers.get('content-type'),/text\/css/);});
test('invalid encoded paths cannot escape the public directory',async()=>{for(const p of ['/%2e%2e%2fpackage.json','/%00foo','/%5c..%5cpackage.json','/%E0%A4%A']){const r=await fetch(base+p);assert.ok([400,403,404].includes(r.status),`${p}: ${r.status}`);}});
test('unknown Host headers are rejected',async()=>{const status=await new Promise((resolve,reject)=>{const req=http.get({hostname:'127.0.0.1',port,headers:{Host:'evil.example'}},r=>{r.resume();resolve(r.statusCode);});req.on('error',reject);});assert.equal(status,403);});
