'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),C=require('../../public/spot/core.js');
const N=1800000000000;
const ctx=()=>({s:C.initialState(),snap:C.makeSnapshot(N)});
const stat=(s,snap,t=N)=>C.populationStats(s,snap,t);
const activity=(id,s,snap,t=N)=>C.activity(C.venueById(id),s,snap,t);
test('5,000 distinct registered demo accounts, including viewer',()=>{assert.equal(C.USERS.length,5000);assert.equal(new Set(C.USERS.map(u=>u.id)).size,5000);assert.equal(C.USERS.filter(u=>u.id==='you').length,1);});
test('60 distinct fictional venue IDs and names',()=>{assert.equal(C.VENUES.length,60);assert.equal(new Set(C.VENUES.map(v=>v.id)).size,60);assert.equal(new Set(C.VENUES.map(v=>v.name)).size,60);});
test('100 distinct named directory profiles',()=>{assert.equal(C.PEOPLE.length,100);assert.equal(new Set(C.PEOPLE.map(p=>p.handle)).size,100);});
test('60 accepted friends, 42 visible, 6 incoming',()=>{const {s,snap}=ctx();const a=stat(s,snap);assert.equal(a.friends,60);assert.equal(a.friendsPresent,42);assert.equal(a.requests,6);});
test('900 mapped, 4,100 unmapped, total 5,000',()=>{const {s,snap}=ctx();assert.deepEqual(stat(s,snap),{total:5000,present:900,notAtVenues:4100,friends:60,friendsPresent:42,requests:6,venues:60});});
test('display counts equal allocated accounts, not an arbitrary population label',()=>{for(const v of C.VENUES)assert.equal(C.USERS.filter(u=>u.venueId===v.id).length,v.people);});
test('all user locations resolve to valid venues or null',()=>C.USERS.forEach(u=>assert.ok(u.venueId===null||C.venueById(u.venueId))));
test('friends are included in the population, not extra people',()=>{for(const p of C.PEOPLE){const u=C.USERS.find(u=>u.id===p.id);assert.ok(u);assert.equal(u.venueId,p.venueId);}});
test('named friend participants cannot exceed a venue count',()=>{const {s,snap}=ctx();for(const v of C.VENUES){const a=C.activity(v,s,snap,N);assert.ok(a.friends.length<=a.count);}});
test('22 areas have demo places; other areas remain on map without invented businesses',()=>assert.equal(new Set(C.VENUES.map(v=>v.area)).size,22));
test('all venue coordinates lie inside configured Lincoln-area bounds',()=>{const b=C.MAP.bounds;for(const v of C.VENUES){assert.ok(v.lat>b.south&&v.lat<b.north);assert.ok(v.lng>b.west&&v.lng<b.east);}});
test('coordinates use the same projection as the map',()=>{for(const v of C.VENUES){const p=C.project(v.lng,v.lat);assert.ok(Math.abs(p.x-v.x)<.02&&Math.abs(p.y-v.y)<.02);}});
test('projection rejects nonfinite coordinates',()=>assert.throws(()=>C.project(NaN,40.8),TypeError));
test('demo initially does not share the viewer',()=>{const {s,snap}=ctx();assert.equal(s.sharing,false);assert.equal(activity('juniper',s,snap).count,18);assert.equal(activity('juniper',s,snap).own,false);});
test('sharing adds one existing account, never a 5,001st account',()=>{const {s,snap}=ctx();C.setSharing(s,snap,true,N);assert.equal(activity('juniper',s,snap).count,19);assert.equal(stat(s,snap).present,901);assert.equal(stat(s,snap).total,5000);assert.equal(stat(s,snap).notAtVenues,4099);});
test('repeated enable does not double count the viewer',()=>{const {s,snap}=ctx();C.setSharing(s,snap,true,N);C.setSharing(s,snap,true,N);assert.equal(activity('juniper',s,snap).count,19);});
test('disabling removes own presence immediately',()=>{const {s,snap}=ctx();C.setSharing(s,snap,true,N);C.setSharing(s,snap,false,N);assert.equal(snap.ownSeenAt,null);assert.equal(activity('juniper',s,snap).count,18);});
test('no recent participants is unknown, not empty',()=>{const {s,snap}=ctx();const a=activity('sunday',s,snap);assert.equal(a.count,0);assert.equal(a.hasData,false);assert.equal(a.latest,null);});
test('all sample presence and friend visibility expires',()=>{const {s,snap}=ctx();assert.equal(stat(s,snap,N+C.TTL).present,0);assert.equal(stat(s,snap,N+C.TTL).friendsPresent,0);assert.equal(stat(s,snap,N+C.TTL).total,5000);});
test('a newly enabled own presence can outlive the sample snapshot',()=>{const {s,snap}=ctx();C.setSharing(s,snap,true,N+C.TTL);assert.equal(activity('juniper',s,snap,N+C.TTL).count,1);assert.equal(activity('juniper',s,snap,N+2*C.TTL).count,0);});
test('strict freshness boundary and future timestamps',()=>{assert.equal(C.isFresh(N,N+C.TTL-1),true);assert.equal(C.isFresh(N,N+C.TTL),false);assert.equal(C.isFresh(N+1,N),false);assert.equal(C.isFresh(null,N),false);});
test('friends-only filter returns only places with accepted visible friends',()=>{const {s,snap}=ctx();s.friendsOnly=true;const vs=C.filteredVenues(s,snap,N);assert.ok(vs.length>20&&vs.length<60);assert.ok(vs.every(v=>C.friendsAt(v.id,s,snap,N).length>0));});
test('friends-only filter empties after expiration',()=>{const {s,snap}=ctx();s.friendsOnly=true;assert.equal(C.filteredVenues(s,snap,N+C.TTL).length,0);});
test('category filters partition the venue directory',()=>{const {s,snap}=ctx();s.category='cafe';const a=C.filteredVenues(s,snap,N);s.category='club';const b=C.filteredVenues(s,snap,N);assert.equal(a.length+b.length,60);assert.ok(a.every(v=>v.category==='cafe'));assert.ok(b.every(v=>v.category==='club'));});
test('Lincoln city search returns full city',()=>{const {s,snap}=ctx();s.query='Lincoln';assert.equal(C.filteredVenues(s,snap,N).length,44);});
test('neighborhood search supports Haymarket',()=>{const {s,snap}=ctx();s.query='Haymarket';assert.equal(C.filteredVenues(s,snap,N).length,10);});
test('search ignores accents and case',()=>assert.equal(C.normalize(' CAFÉ '),'cafe'));
test('unmatched search returns no venues',()=>{const {s,snap}=ctx();s.query='xyz123-not-a-place';assert.equal(C.filteredVenues(s,snap,N).length,0);});
test('accepting an incoming request adds identity, not another venue participant',()=>{const {s,snap}=ctx();const before=activity('common',s,snap).count;assert.equal(C.friendVisible(C.personById('alex'),s,snap,N),false);assert.ok(C.changeRelation(s,'alex','accept'));assert.equal(stat(s,snap).friends,61);assert.equal(stat(s,snap).friendsPresent,43);assert.equal(activity('common',s,snap).count,before);});
test('removal hides identity without changing the count',()=>{const {s,snap}=ctx();assert.ok(C.changeRelation(s,'maya','remove'));assert.equal(C.friendVisible(C.personById('maya'),s,snap,N),false);assert.equal(activity('juniper',s,snap).count,18);});
test('blocking and unblocking do not implicitly re-add friendship',()=>{const {s,snap}=ctx();assert.ok(C.changeRelation(s,'maya','block'));assert.ok(C.changeRelation(s,'maya','unblock'));assert.equal(s.relations.maya,undefined);assert.equal(C.friendVisible(C.personById('maya'),s,snap,N),false);});
test('sending a request leaves it pending',()=>{const {s,snap}=ctx();assert.ok(C.changeRelation(s,'jordan','request'));assert.equal(s.relations.jordan,'sent');assert.equal(C.friendVisible(C.personById('jordan'),s,snap,N),false);});
test('cancel and decline remove pending connections',()=>{const {s}=ctx();C.changeRelation(s,'jordan','request');assert.ok(C.changeRelation(s,'jordan','cancel'));assert.ok(C.changeRelation(s,'alex','decline'));assert.equal(s.relations.jordan,undefined);assert.equal(s.relations.alex,undefined);});
test('invalid actions and people are rejected',()=>{const {s}=ctx();assert.equal(C.changeRelation(s,'no-such-person','accept'),false);assert.equal(C.changeRelation(s,'maya','accept'),false);assert.equal(C.changeRelation(s,'alex','weird'),false);});
test('not-sharing friends do not reveal a venue',()=>{const {s,snap}=ctx();assert.equal(C.friendVisible(C.personById('sam'),s,snap,N),false);});
test('persistence keeps the v4 preference contract without runtime state',()=>{const {s}=ctx();assert.deepEqual(Object.keys(C.persistent(s)),['version','sharing','friendSharing','shareWith','savedVenues','relations']);assert.equal(C.persistent(s).version,4);});
test('restoring preferences does not replace local fixtures or account count',()=>{const {s}=ctx();s.sharing=true;C.changeRelation(s,'maya','remove');const next=C.initialState(C.persistent(s));assert.equal(next.sharing,true);assert.equal(next.relations.maya,undefined);assert.equal(C.USERS.length,5000);});
test('old-version state is safely replaced by the larger default fixture',()=>{const s=C.initialState({version:1,sharing:true,relations:{}});assert.equal(s.sharing,false);assert.equal(Object.values(s.relations).filter(r=>r==='accepted').length,60);});
test('unrecognized saved relation values cannot grant access',()=>{const s=C.initialState({version:2,sharing:'yes',relations:{maya:'admin',unknown:'accepted'}});assert.equal(s.sharing,false);assert.deepEqual(s.relations,{});});
test('time labels never imply fresh data for missing timestamps',()=>{assert.equal(C.timeLabel(null,N),'No recent activity');assert.equal(C.timeLabel(N,N),'Just now');assert.equal(C.timeLabel(N-120000,N),'2 min ago');});
