'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const C=require('../../public/spot/core.js'),M=require('../../public/spot/map-core.js'),S=require('../../public/spot/place-search.js');
const vs=[C.venueById('juniper'),C.venueById('common')];
const live=count=>({count,hasData:true,friends:[]});
const missing={count:0,hasData:false,friends:[]};
test('venue marker says whose count it is rather than showing a bare number',()=>{const m=M.describeMarker([vs[0]],[live(18)]);assert.equal(m.heading,'Juniper');assert.equal(m.countText,'18 app users');assert.match(m.label,/Juniper Coffee/);assert.match(m.label,/Not total occupancy/);});
test('one participating user uses singular copy',()=>assert.equal(M.describeMarker([vs[0]],[live(1)]).countText,'1 app user'));
test('groups display place count separately from participant count',()=>{const m=M.describeMarker(vs,[live(18),live(12)]);assert.equal(m.heading,'2 nearby spots');assert.equal(m.countText,'30 app users');assert.equal(m.count,30);assert.equal(m.grouped,true);assert.match(m.label,/Tap to explore/);});
test('unknown venue is never shown as zero or empty',()=>{const m=M.describeMarker([vs[0]],[missing]);assert.equal(m.countText,'No recent data');assert.equal(m.known,false);assert.ok(!/empty|quiet|full/i.test(m.label));});
test('a group with no recent observations stays unknown',()=>{const m=M.describeMarker(vs,[missing,missing]);assert.equal(m.countText,'No recent data');assert.equal(m.count,0);assert.equal(m.reportingVenues,0);});
test('mixed-coverage group reports the count and identifies missing coverage',()=>{const m=M.describeMarker(vs,[live(18),missing]);assert.equal(m.count,18);assert.match(m.label,/1 of 2 spots; others are unknown/);});
test('expired or explicitly unknown observations do not inflate a count',()=>{const m=M.describeMarker(vs,[live(18),{count:900,hasData:false}]);assert.equal(m.count,18);});
test('invalid observations cannot create NaN, negative, or infinite counts',()=>{for(const count of [NaN,Infinity,-4,0])assert.equal(M.describeMarker([vs[0]],[live(count)]).known,false);});
test('marker numeric text formats thousands readably',()=>assert.equal(M.describeMarker([vs[0]],[live(1500)]).countText,'1,500 app users'));
test('marker description does not mutate incoming data',()=>{const a=[live(18)];const before=JSON.stringify(a);M.describeMarker(vs,a);assert.equal(JSON.stringify(a),before);});
test('all fictional venues are at least 600 meters apart',()=>{for(let i=0;i<C.VENUES.length;i++)for(let j=i+1;j<C.VENUES.length;j++)assert.ok(S.distance(C.VENUES[i],C.VENUES[j])>=600,`${C.VENUES[i].id}/${C.VENUES[j].id}`);});
test('every place has a unique authored display name',()=>assert.equal(new Set(C.VENUES.map(v=>v.name)).size,32));
test('every visible count fits within the registered-account allocation',()=>{assert.equal(C.USERS.length,5000);assert.equal(C.VENUES.reduce((n,v)=>n+v.people,0),610);});
test('bars keyword reaches the same eight nightlife records as clubs',()=>{const s=C.initialState(),snap=C.makeSnapshot();s.query='bars';assert.equal(C.filteredVenues(s,snap,Date.now()).length,8);});
test('prototype documentation agrees with the current authored fixture',()=>{const text=fs.readFileSync(path.join(__dirname,'../../docs/PROTOTYPE-DATA.md'),'utf8');for(const phrase of ['32 fictional venues','24 cafés','8 bars / clubs','610 sample users'])assert.ok(text.includes(phrase),phrase);});
test('new service-worker shell version does not reuse the old map shell name',()=>{const text=fs.readFileSync(path.join(__dirname,'../../public/sw.js'),'utf8');assert.match(text,/spot-map-4\.7\.0/);assert.ok(!text.includes("VERSION='spot-ai-4.6.0'"));});
test('cards have deliberate 52-pixel touch surfaces',()=>{const css=fs.readFileSync(path.join(__dirname,'../../public/spot/brand.css'),'utf8');assert.match(css,/\.activity-marker\{[^}]*height:52px/);assert.match(css,/\.activity-marker-card\{[^}]*height:52px/);});
test('camera fit reserves room for wider readable marker cards',()=>{const l=S.exact('East Campus'),d={width:390,height:535},camera=S.cameraFor(l,d);assert.equal(camera.x,l.x);assert.equal(camera.y,l.y);assert.ok(camera.zoom<1);});
test('sample area center and original regional boundaries are not stretched',()=>{const d=C.MAP;assert.deepEqual(d.bounds,{west:-97.13,east:-96.37,south:40.55,north:41.07});assert.equal(S.locations.length,40);});
test('new clustering still conserves participant counts at every tested zoom',()=>{const s=C.initialState(),snap=C.makeSnapshot(),t=Date.now();for(const z of [.025,.06,.12,.4,.6,1,1.4,2,4,8]){const ids=M.cluster(C.VENUES,z,null,M.markerSpacing(z,true)).flatMap(g=>g.ids);assert.equal(new Set(ids).size,32);assert.equal(ids.reduce((sum,id)=>sum+C.activity(C.venueById(id),s,snap,t).count,0),610);}});
