'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const S=require('../../public/spot/place-search.js'),C=require('../../public/spot/core.js');
test('forty area centers have unique stable IDs',()=>{assert.equal(S.locations.length,40);assert.equal(new Set(S.locations.map(l=>l.id)).size,40);});
test('every canonical name resolves to itself, including East Lincoln',()=>{for(const l of S.locations)assert.equal(S.exact(l.name)?.id,l.id,l.name);});
test('every complete alias resolves correctly',()=>{for(const l of S.locations)for(const alias of l.aliases)assert.equal(S.exact(alias)?.id,l.id,alias);});
test('East Campus resolves by full name and UNL shorthand',()=>{for(const q of ['East Campus','UNL East Campus','unl east','eastcampus','EAST CAMPUS','  East   Campus  '])assert.equal(S.exact(q)?.id,'unl-east-campus');});
test('Lincoln and state qualifiers are accepted',()=>{for(const q of ['East Campus, Lincoln NE','East Campus in Lincoln Nebraska','East Campus, Nebraska','East Campus NE'])assert.equal(S.exact(q)?.id,'unl-east-campus');});
test('near/around/take-me-to are recognized',()=>{for(const q of ['near East Campus','around East Campus','take me to East Campus','show me East Campus'])assert.equal(S.exact(q)?.id,'unl-east-campus');});
test('matching preserves the real map projection',()=>{for(const l of S.locations){const p=C.project(l.lng,l.lat);assert.ok(Math.abs(p.x-l.x)<1e-6&&Math.abs(p.y-l.y)<1e-6);}});
test('all centers are inside supported Lincoln-region bounds',()=>{for(const l of S.locations){assert.ok(l.lng>C.MAP.bounds.west&&l.lng<C.MAP.bounds.east);assert.ok(l.lat>C.MAP.bounds.south&&l.lat<C.MAP.bounds.north);}});
test('East Campus is northeast of City Campus',()=>{const a=S.exact('East Campus'),b=S.exact('City Campus');assert.ok(a.lat>b.lat&&a.lng>b.lng);});
test('East Campus shows nearby venues whose names do not contain East Campus',()=>{const vs=S.nearby(C.VENUES,S.exact('East Campus'));assert.equal(vs.length,3);assert.ok(vs.every(v=>!v.name.includes('East Campus')));});
test('nearby places are nearest-first, measured from area not device',()=>{const l=S.exact('East Campus'),vs=S.nearby(C.VENUES,l),ds=vs.map(v=>S.distance(v,l));assert.deepEqual(ds,[...ds].sort((a,b)=>a-b));});
test('all nearby results are inside stated radius',()=>{for(const l of S.locations)for(const v of S.nearby(C.VENUES,l))assert.ok(S.distance(v,l)<=l.radiusMeters);});
test('search does not invent nearby venues for an empty area',()=>{assert.deepEqual(S.nearby(C.VENUES,{lat:41,lng:-97,radiusMeters:20}),[]);});
test('partial east is ambiguous and never auto-jumps',()=>{assert.equal(S.exact('east'),null);assert.deepEqual(S.matches('east').map(l=>l.name),['East Campus','East Lincoln']);});
test('typo suggestions do not cause automatic camera jumps',()=>{assert.equal(S.exact('East Campu'),null);assert.ok(S.matches('East Campu').some(l=>l.name==='East Campus'));});
test('unknown regions and addresses do not resolve to fabricated coordinates',()=>{for(const q of ['New York','Omaha','Mars','9999 imaginary st','<script>alert(1)</script>'])assert.equal(S.exact(q),null);});
test('very short inputs cannot auto-jump',()=>{for(const q of ['','a','ne','\n'])assert.equal(S.exact(q),null);});
test('search suggestions are stable and capped',()=>{assert.deepEqual(S.matches('campus'),S.matches('campus'));assert.ok(S.matches('a',3).length<=3);});
test('initial suggestions include East Campus',()=>{assert.equal(S.matches('')[0].name,'East Campus');});
test('distance calculation is symmetric and zero at same coordinates',()=>{const a=S.exact('East Campus'),b=S.exact('City Campus');assert.equal(S.distance(a,a),0);assert.ok(Math.abs(S.distance(a,b)-S.distance(b,a))<1e-7);});
test('radius and distance use miles without suggesting driving distance',()=>{assert.equal(S.distanceLabel(1609.344),'1.0 mi');assert.equal(S.distanceLabel(100),'< 0.1 mi');assert.equal(S.radiusLabel(S.exact('East Campus')),'1.0 mi area');assert.equal(S.distanceLabel(NaN),'');});
test('camera centers exactly on landmark without relying on venue-name results',()=>{const l=S.exact('East Campus');for(const d of [{width:390,height:535},{width:987,height:877}]){const c=S.cameraFor(l,d);assert.equal(c.x,l.x);assert.equal(c.y,l.y);assert.ok(c.zoom>.025&&c.zoom<=2);}});
test('camera handles narrow map dimensions',()=>{for(const l of S.locations){const c=S.cameraFor(l,{width:100,height:100});assert.ok(Number.isFinite(c.zoom)&&c.zoom>=.025);}});
test('category/friends/saved filtering remains composable with area radius',()=>{const state=C.initialState(),snap=C.makeSnapshot(),t=Date.now(),area=S.exact('East Campus');state.category='cafe';let vs=S.nearby(C.filteredVenues(state,snap,t),area);assert.ok(vs.length&&vs.every(v=>v.category==='cafe'));state.savedOnly=true;state.savedVenues=[vs[0].id];assert.deepEqual(S.nearby(C.filteredVenues(state,snap,t),area).map(v=>v.id),state.savedVenues);});
test('real landmarks are not injected into population or fictional venues',()=>{assert.equal(C.VENUES.length,32);assert.equal(C.populationStats(C.initialState(),C.makeSnapshot(),Date.now()).present,610);assert.equal(C.POPULATION,5000);});
test('changing search leaves fixture data byte-identical',()=>{const before=JSON.stringify(C.VENUES);for(const l of S.locations){S.nearby(C.VENUES,l);S.matches(l.name);}assert.equal(JSON.stringify(C.VENUES),before);});
test('search module makes no network or geolocation calls',()=>{const s=fs.readFileSync(path.join(__dirname,'../../public/spot/place-search.js'),'utf8');assert.ok(!/fetch\s*\(|XMLHttpRequest|navigator\.geolocation/.test(s));});
test('brand icon is a signal ring, not the old pin',()=>{const s=fs.readFileSync(path.join(__dirname,'../../public/spot/assets/spot-mark.svg'),'utf8');assert.match(s,/#6250E8/);assert.match(s,/#FF947D/);assert.ok(!s.includes('M44 28'));});
test('rollback of v4.2 remains byte identical to supplied original',()=>{const h=x=>crypto.createHash('sha256').update(fs.readFileSync(x)).digest('hex');assert.equal(h(path.join(__dirname,'../../rollback/spot-lincoln-v4.2.html')),'60ba198e9317379e560c395e7aa5f4c3841a7f59935a94e02aaf1482ba47982f');});
