'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),crypto=require('node:crypto');
const C=require('../../public/spot/core.js'),M=require('../../public/spot/map-core.js'),seed=require('../fixtures/fixture-seed-v43.json');
const dims={width:390,height:595,centerX:195,centerY:232.5},camera={x:4500,y:4000,zoom:.06};
test('curated sample contains exactly fifty cafes and ten clubs; no third category',()=>{assert.equal(C.VENUES.filter(v=>v.category==='cafe').length,50);assert.equal(C.VENUES.filter(v=>v.category==='club').length,10);assert.equal(C.VENUES.length,60);});
test('sample is forty-four Lincoln venues and sixteen in surrounding towns',()=>{const city=new Set(C.MAP.areas.filter(a=>!a.regional).map(a=>a.name));assert.equal(C.VENUES.filter(v=>city.has(v.area)).length,44);assert.equal(C.VENUES.filter(v=>!city.has(v.area)).length,16);});
test('all club placeholders are limited to three city areas, not spread into rural towns',()=>{const clubs=C.VENUES.filter(v=>v.category==='club');assert.ok(clubs.every(v=>['Haymarket','Downtown','Havelock'].includes(v.area)));});
test('small-town samples never exceed three cafes each',()=>{for(const a of C.MAP.areas.filter(a=>a.regional)){const vs=C.VENUES.filter(v=>v.area===a.name);assert.ok(vs.length<=3);assert.ok(vs.every(v=>v.category==='cafe'));}});
test('surviving place IDs retain their coordinates and identities',()=>{for(const v of C.VENUES){const old=seed.venues.find(o=>o.id===v.id);assert.ok(old);assert.equal(v.name,old.name.replace(/\bBar\b/g,'Club'));for(const k of ['lat','lng','x','y'])assert.equal(v[k],old[k]);}});
test('all named friend IDs remain the same across revisions',()=>assert.deepEqual(C.PEOPLE.map(p=>p.id),seed.people.map(p=>p.id)));
test('friend visits reattach to real surviving fixtures with current venue timestamps',()=>{for(const p of C.PEOPLE)if(p.venueId){const v=C.venueById(p.venueId);assert.ok(v);assert.equal(p.age,v.age);}});
test('only nine hundred accounts appear at venues, not all five thousand',()=>{assert.equal(C.USERS.filter(u=>u.venueId).length,900);assert.equal(C.USERS.filter(u=>!u.venueId).length,4100);});
test('sample count limits are conservative by category, not real capacity claims',()=>{assert.ok(C.VENUES.filter(v=>v.category==='cafe').every(v=>v.people<=28));assert.ok(C.VENUES.filter(v=>v.category==='club').every(v=>v.people<=90));});
test('removed bookmarks are discarded, retained bookmarks keep identity',()=>{const dropped=seed.venues.find(v=>!C.venueById(v.id));const state=C.initialState({version:4,savedVenues:['juniper',dropped.id],relations:C.DEFAULT_RELATIONS});assert.deepEqual(state.savedVenues,['juniper']);});
test('club category and nightclub search agree with the catalog',()=>{const state=C.initialState(),snap=C.makeSnapshot();state.category='club';assert.equal(C.filteredVenues(state,snap,Date.now()).length,10);state.category='all';state.query='nightclub';assert.equal(C.filteredVenues(state,snap,Date.now()).length,10);});
test('group drill-down centers on member bounds and increases scale',()=>{const members=[{x:5000,y:4000},{x:5100,y:4100}];const n=M.drillDownCamera(members,camera,dims);assert.equal(n.x,5050);assert.equal(n.y,4050);assert.ok(n.zoom>camera.zoom);});
test('drill-down fits a local group inside the usable map, not behind bottom chrome',()=>{const points=[{x:5000,y:4000},{x:5100,y:4100}];const n=M.drillDownCamera(points,camera,dims);for(const v of points){const p=M.project(v,n,dims);assert.ok(p.x>=54&&p.x<=dims.width-54);assert.ok(p.y>=66&&p.y<=dims.height-190);}});
test('repeat group navigation still moves inward but respects maximum zoom',()=>{const points=[{x:5000,y:4000},{x:5001,y:4001}];assert.equal(M.drillDownCamera(points,{...camera,zoom:8},dims).zoom,8);assert.ok(M.drillDownCamera(points,{...camera,zoom:1},dims).zoom>1);});
test('empty or invalid drill-down members are a no-op',()=>{assert.deepEqual(M.drillDownCamera([],camera,dims),camera);assert.deepEqual(M.drillDownCamera([{x:NaN,y:3}],camera,dims),camera);});
test('drill-down does not mutate its input camera or places',()=>{const cc={...camera},pts=[{x:1,y:2},{x:3,y:4}],before=JSON.stringify(pts);M.drillDownCamera(pts,cc,dims);assert.deepEqual(cc,camera);assert.equal(JSON.stringify(pts),before);});
test('drill-down remains finite for compact or landscape map dimensions',()=>{for(const d of [dims,{width:260,height:220,centerX:130,centerY:95},{width:740,height:280,centerX:370,centerY:95}]){const n=M.drillDownCamera([{x:12,y:12},{x:32,y:42}],camera,d);assert.ok(Number.isFinite(n.zoom)&&n.zoom>.025&&n.zoom<=8);}});
test('unchanged v4.3 is included as a byte-identical rollback',()=>{const hash=f=>crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex');assert.equal(hash(require('node:path').join(__dirname,'../../rollback/spot-lincoln-v4.3.html')),process.env.SPOT_V43_SHA||'ed82ee5fe9490800f39dec40252d0f07b3a4a8892b3c5853a800da86dbe72d7a');});
test('single-finger/pinch gesture engine is unchanged from v4.3',()=>{const html=fs.readFileSync(require('node:path').join(__dirname,'../../rollback/spot-lincoln-v4.3.html'),'utf8');const current=fs.readFileSync(require('node:path').join(__dirname,'../../public/spot/map-gestures.js'),'utf8').trim();assert.ok(html.includes(current));});
test('selected name finds a free nearby slot in a dense mobile group without overlapping pins',()=>{
 const selected={key:'v:juniper',x:105.288,y:223.376,pinWidth:58,width:83,offset:26,priority:0};
 const obstacles=[{x:74.288,y:206.376,w:62,h:38},{x:119.9,y:170.816,w:55,h:34},{x:59.983,y:245.569,w:54,h:34},{x:39.829,y:166.905,w:55,h:34},{x:141.804,y:219.662,w:50,h:34}];
 const labels=M.labelLayout([selected],{x:10,y:62,w:370,h:340},obstacles);
 assert.equal(labels.length,1);assert.equal(labels[0].key,selected.key);
 assert.ok(obstacles.every(o=>!M.intersects(labels[0],o,5)));
 assert.ok(Math.abs(labels[0].y-selected.y)<=90);
});
