'use strict';
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const read = file => fs.readFileSync(path.join(root, file), 'utf8');
let html = read('index.html');
html = html.replace('<link rel="stylesheet" href="styles.css">', () => `<style>\n${read('styles.css')}\n</style>`);
html = html.replace('<link rel="stylesheet" href="brand.css">', () => `<style>\n${read('brand.css')}\n</style>`);
for (const name of ['lincoln-data.js','core.js','place-search.js','map-core.js','map-gestures.js','map-renderer.js','theme.js','app.js']) html = html.replace(`<script src="${name}"></script>`, () => `<script>\n${read(name).replace(/<\/script/gi, '<\\/script')}\n</script>`);
const target = path.join(root, 'dist'); fs.mkdirSync(target, { recursive: true });
fs.writeFileSync(path.join(target, 'spot-prototype.html'), html);
console.log('Built dist/spot-prototype.html (self-contained; offline regional map included; no network or GPS).');
